<a href="https://colab.research.google.com/github/ArminVarmaz/DE_DA/blob/main/Termin_1/Termin_1_20230224.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Termin

**Ziele des 1. Termins (Einführung)**

- [Nutzung von Colab und GitHub für Lehrbeispiele](https://colab.research.google.com/drive/1q0-tSPquK8EFjNDSIAXPRI04TW7VCr5o#scrollTo=70a0337e) 
- [Kurzeinführung in Python](https://colab.research.google.com/drive/1q0-tSPquK8EFjNDSIAXPRI04TW7VCr5o#scrollTo=kor-LKUt85wt)
- [Instalation einer IDE am Beispiel von PyCharm](https://colab.research.google.com/drive/1q0-tSPquK8EFjNDSIAXPRI04TW7VCr5o#scrollTo=bce2a334)  
- Nutzung von PyCharm
- Skripte ausführen in PyCharm
- Nutzung von ChatGPT
- Einfache Datenanalyse

# Google Colab
Diese Datei folgt nicht dem Standardmuster mit Python-Code in einer Textdatei. Stattdessen wird ein Colab-Notizbuch als Datei gespeichert. Der Vorteil ist, dass wir formatierten Text, Python-Code und Code-Ausgabe mischen können. Zur Ausführung ist allerdings der Jupyter-Notizbuch-Server erforderlich, es handelt sich also nicht um ein eigenständiges Python-Programm. Ansonsten gibt es keinen Unterschied zwischen dem Python-Code, der in einer Programmdatei oder einem Jupyter-Notizbuch enthalten ist.

Eine kurze Einführung in [Colab](https://colab.research.google.com) wird von Google mit vielen Datenanalyse-Beispielen aufgezeigt.


## Colab-Benutzeroberfläche



Zwei Begriffe, die Ihnen wahrscheinlich neu sind, sollten Sie unbedingt kennenlernen: Zellen und Kernel.
- Ein Kernel ist eine "Rechenmaschine", die den in einem Notizbuchdokument enthaltenen Code ausführt.
- Eine Zelle ist ein Container für Text, der im Notizbuch angezeigt wird, oder für Code, der vom Kernel des Notizbuchs ausgeführt wird.

### Zellen

Eine Codezelle enthält Code, der im Kernel ausgeführt werden soll. Wenn der Code ausgeführt wird, zeigt das Notizbuch die Ausgabe unterhalb der Codezelle an, die ihn erzeugt hat.

Eine Markdown-Zelle enthält Text, der mit Markdown formatiert wurde, und zeigt seine Ausgabe an Ort und Stelle an, wenn die Markdown-Zelle ausgeführt wird.

Die erste Zelle in einem neuen Notizbuch ist immer eine Codezelle.

Probieren wir es mit einem klassischen Hallo-Welt-Beispiel aus: Geben Sie `print("Hello World!")` in die Zelle ein und klicken Sie auf die Schaltfläche Notebook Run Button in der Symbolleiste oben oder drücken Sie Strg + Enter.

Das Ergebnis sollte wie folgt aussehen:

In [ ]:
print("Hallo Welt, ich bin da!")

Hallo Welt, ich bin da!


### Kernel
Hinter jedem Notebook verbirgt sich ein sog. Kernel. Wenn Sie eine Codezelle ausführen, wird dieser Code im Kernel ausgeführt. Alle Ausgaben werden an die Zelle zurückgegeben, um angezeigt zu werden. Der Zustand des Kerns bleibt über die Zeit und zwischen den Zellen bestehen - er bezieht sich auf das Dokument als Ganzes und nicht auf einzelne Zellen.




## Versionskontrolle: Git und GitHub

Die Versionskontrolle ist ein wesentlicher Bestandteil der Codierung und der Teamarbeit. Sie stellt sicher, dass Sie beim Schreiben eines Codes für eine Analyse oder bei der Entwicklung eines Codes/Pakets/Materials den Überblick über Ihre Fortschritte behalten. Meine Empfehlung an Sie: eignen Sie sich diese gute Gewohnheit während dieses Kurses an und nutzen Sie aktiv GitHub. 

Es gibt mehrere Möglichkeiten der Versionskontrolle, die alle einige Vor- und Nachteile haben. Hier listen wir die drei am häufigsten verwendeten auf:

- [GitHub Desktop](https://desktop.github.com/) (und [friends](https://www.slant.co/options/13488/alternatives/~github-desktop-alternatives)\):
  - Anwendung zum bequemen Verfolgen von Änderungen, Commit, Pull und Push auf GitHub
  - Pro: einfach zu benutzen, flexibel für alle Arten von Dateien, hilft Konflikte zu vermeiden
  - Contra: zusätzliche Anwendung, sollte zur Gewohnheit werden und nicht vergessen werden

- Shell/Terminal
  - Verwendung von Shell oder Terminal für die Versionskontrolle
  - Pro: flexibel für alle Arten von Dateien, kann buchstäblich alles damit machen
  - Nachteil: schwerer zu erlernen, kann Fehler machen, die schwer zu korrigieren sind
  
Es spielt keine Rolle, was Sie verwenden, Hauptsache, Sie nutzen die Versionskontrolle. Sie macht Ihr Leben viel einfacher, besonders bei komplizierten Projekten, bei denen Sie verschiedene Richtungen testen und ausprobieren müssen. [GitHub](https://github.com/) ist eine gute Plattform für die Zusammenarbeit, aber es gibt auch noch andere.

In diesem Kurs gebe ich keinen Überblick darüber, wie Versionskontrolle funktioniert. Nützliches Material finden Sie unter:
  - Technische Grundlagen der Informatik Buch: https://info201.github.io/git-basics.html
  - Software Carpentry Kurs (sehr zu empfehlen): https://swcarpentry.github.io/git-novice/
  - Github Lernlabor: https://lab.github.com/

Ein Beispiel für diesen Kurs: https://github.com/ArminVarmaz/DE_DA.git 

# Einführung in Python

Python ist eine interpretierte, objektorientierte Programmiersprache, die eine klare und einfache Syntax hat. Python eignet sich hervorragend für schnelle Prototypen und Skripte sowie für die Entwicklung großer Anwendungen.

Hier sind einige wichtige Konzepte, die in Python verwendet werden:

* Variablen: In Python können wir Variablen definieren, um Werte zu speichern. Eine Variable wird erstellt, indem wir einen Namen zuweisen und ihm einen Wert zuweisen. Der Wert kann jeder Datentyp sein, einschließlich Zahlen, Zeichenketten oder Booleans.
* Datentypen: Python unterstützt eine Vielzahl von Datentypen, darunter Integer, Floats, Zeichenketten und Booleans. Wir können auch komplexe Datentypen wie Listen, Tupel und Wörterbücher verwenden.
* Kontrollstrukturen: Python unterstützt verschiedene Kontrollstrukturen wie if-Anweisungen, Schleifen und Funktionen. Wir können diese Kontrollstrukturen verwenden, um das Verhalten Ihrer Anwendung zu steuern.
* Funktionen: Funktionen sind ein grundlegendes Konzept in Python. Wir können eine Funktion erstellen, um bestimmte Aufgaben auszuführen. Eine Funktion kann Parameter akzeptieren und Werte zurückgeben.
* Module: In Python können wir Code in Modulen organisieren. Ein Modul ist eine Sammlung von Funktionen und Variablen, die in einer Datei gespeichert sind. Wir können Module in Ihre Anwendung importieren und die darin enthaltenen Funktionen verwenden.

Diese Konzepte bilden die Grundlage für das Verständnis von Python und sind wichtig, um die Sprache zu erlernen. Wenn Sie diese Konzepte verinnerlicht haben, können Sie damit beginnen, Python-Anwendungen zu entwickeln und komplexe Aufgaben zu automatisieren.


## "Taschenrechner"

In der einfachsten Variante können wir Python und Colab als Taschenrechner nutzen.

In [ ]:
1 + 3



4

## Kommentare schreiben

Es ist gute Praxis, den Code mit ausreichend viel Kommentaren zu versehen, damit wir selbst nach einigen Monaten und vor allem Dritte wissen, welchen Zweck der Codeabschnitt hat. 

Kommentierung werden in Python mit dem Zweichen # eingeführt.

In [ ]:
# Erster Versuch
a = 1
b = 22
# Führe eine Berechnung mit den Variablen a und b durch und weise das Ergebnis der Variable c zu
c = a + b
# Gib das Ergebnis von c auf der Konsole aus
print(c)
# Erzeuge Variable d und weise ihr Text (String) zu
d = "Das ist der Wert von Variable c: "
# Gib den Wert von d aus
print(d)
# Verknüpfung von Text und Zahl. Dazu wird die Zahl in das Datentyp String umgewandelt 
e = d + str(c);
# Gib den Wert von e aus
print(e)

434.7826086956522

## Variablen erzeugen

- Variablennamen sollen aus Buchstaben, Unterstrich _ und Ziffern bestehen, keine Leerzeichen nutzen! 
-Variablenname muss mit einem Buchstaben oder Unterstrich _ starten. 
-Python ist case-sensitive, d.h., Klein- und Großschreibung bei der Bezeichnung von Variablen beachten. Variable a ist i.d.R. etwas anders als Variable A.
-Wenn wir einen Variablennamen zweimal nutzen, wird der Inhalt überschrieben/ersetzt durch den neuen Wert.

In [ ]:
# Erzeuge Variable a und b und belege sie mit Zahlen.
a = 1
b = 22
# Führe eine Berechnung mit den Variablen a und b durch und weise das Ergebnis der Variable c zu
c = a + b
# Gib das Ergebnis von c auf der Konsole aus
print(c)
# Wir haette auch dies machen können
print(a+b)
# Erzeuge Variable d und weise ihr Text (String) zu
d = "Das ist der Wert von Variable c: "
# Gib den Wert von d aus
print(d)

# mehhreren Variablen mehrere Werte zuordnen
x, y, z = "Orange", "Bananen", "Kirsche"
print(x)
print(y)
print(z)

# mehhreren Variablen einen Werte zuordnen
x = y = z = "Blaubeere"
print(x)
print(y)
print(z)

obst = ["Apfel", "Bananen", "Kirsche"]
x, y, z = obst
print(x)
print(y)
print(z)

23
23
Das ist der Wert von Variable c: 
Orange
Bananen
Kirsche
Blaubeere
Blaubeere
Blaubeere
Apfel
Bananen
Kirsche


Variablen können wie bisher außerhalb von Funktionen in einem Skript definiert werden. In diesem Fall bezeichnen wir diese Variablen als global

Variablen können auch in einer Funktion definiert werden. Dann wird Ihnen nur in der Funktion der Wert zugewiesen und nur in der Funktion können wir auf diesen Wert zugreifen. Außerhalb der Funktion können wir den Wert nicht nutzen. Deswegen werden diese Variablen als lokale Variablen bezeichnet.




In [ ]:
x = "toll"

# Unsere erste Funktion! Aber dazu später mehr
def myfunc():
  x = "fantastisch"
  print("Python is " + x)

myfunc() # hier wird auf die lokale Variable zugegriffen

print("Python is " + x) # hier wird auf die globale Variable zugegriffen

Python is fantastisch
Python is toll


Wenn wir unbedingt und mit sehr sehr gutem Grund global auf den Wert einer lokalen Variable zugreifen wollten, können wir innerhalb der Funktion  auf d

## Datentypen

Typischerweise wird einer Variable ein Wert vom bestimmten Datentyp zugewiesen. Im obigen Beispiel haben wir zwei Datentypen kennengerlent: Integer und String. 

Mit dem Befehl ```type()``` können wir den Datentyp ermitteln und dann mittels ```print()``` ausgeben lassen. 

Die Verknüpfungen, egal ob zwischen Zahlen und Zahlen, oder Strings und Strings, oder zwischen anderen Datentypen oder zwischen Kombinationen unterschieldicher Datentypen wird als Konkatenation (engl. Concatenation) bezeichnet.

In [ ]:
# Erzeuge Variable a und b und belege sie mit Zahlen.
a = 1
b = 22
# Führe eine Berechnung mit den Variablen a und b durch und weise das Ergebnis der Variable c zu
c = a + b
print(type(c))
# Erzeuge Variable d und weise ihr Text (String) zu
d = "Das ist der Wert von Variable c: "
print(type(d))
# Verknüpfung von Text und Zahl. Dazu wird die Zahl in das Datentyp String umgewandelt
e = d + str(c);
# Gib den Wert von e aus
print(e)
print(type(e))

# Eine andere mögliche Verknüpfung mit der Funktion format
f = "Das ist der Wert von Variable c {} "
print(e.format(c))


<class 'int'>
<class 'str'>
Das ist der Wert von Variable c: 23
<class 'str'>
Das ist der Wert von Variable c: 23


Neben diesen beiden Datentypen kennt Python eine Reihe weiterer Typen, die hier examplarisch dargestellt werden. Eine detailierte Liste und Beschreibung von Datentypen ist in der offiziellen [Dokumentation](https://docs.python.org/3/library/datatypes.html) von Python zu finden. 

In [ ]:
x = "Hello World"	                            # str	
print(x)
x = 20	                                      # int	
print(x)
x = -20.5	                                    # float	
print(x)
x = 1j	                                      # complex	
print(x)
x = ["apple", "banana", "cherry"]	            # list	
print(x)
x = ("apple", "banana", "cherry")	            # tuple	
print(x)
x = range(6)	                                # range	
print(x)
x = {"name" : "John", "age" : 36}	            # dict	
print(x)
x = {"apple", "banana", "cherry"}	            # set	
print(x)
x = frozenset({"apple", "banana", "cherry"})	# frozenset	
print(x)
x = True	                                    # bool	
print(x)
x = b"Hello"	                                # bytes	
print(x)
x = bytearray(5)	                            # bytearray	
print(x)
x = memoryview(bytes(5))	                    # memoryview	
print(x)
x = None	                                    #  NoneType	



Hello World
20
-20.5
1j
['apple', 'banana', 'cherry']
('apple', 'banana', 'cherry')
range(0, 6)
{'name': 'John', 'age': 36}
{'cherry', 'apple', 'banana'}
frozenset({'cherry', 'apple', 'banana'})
True
b'Hello'
bytearray(b'\x00\x00\x00\x00\x00')


Die dargestellten Datentypen können wir mit den Befehlen, die als Kommentar gesetzt sind, erstellen, um Verwechselungen zu vermeiden. Nachfolgend einige Beispiel:

In [ ]:
x = str("Hallo Welt")
print(x)
x = float(20)
print(x)
x = int(20)
print(x)

Hallo Welt
20.0
20


## Zufallszahlen

Für das Testen des eigenen Codes und für die Zwecke von Simulationen benötigen wir Zufallszahlen. Das Grundprogramm von Python kann diese Aufgabe nicht hinreichend gut erledigen. Aber es gibt viele sog. Bibliotheken, die Python erweitern. Dazu später mehr. Wichtig an dieser Stelel ist die Kenntnis, dass wir für die Erzeugung von Zufallszahlen die Bibliothek ```random``` benötigen.

Bei dem Nacharbeiten lohnt es sich, die Zufallszahlen wiederholt berechnen zu lassen. Die Zahl sollte sich ändern.

Ein letzter Hinweis: Computer sind deterministische Maschienen, die an sich 'Zufall nicht können'. Es gibt verschiedene Algorithmen zur Erzeucgung von Zufallszahlen. Diese Algorithmen erstellen Pseudo-Zufallszahlen, die sich, wenn der Algorithmus gut ist, nicht von echten Zufallszahlen statistisch unterscheiden lassen. Die Prüfung der Eigenschaften vom Python-Zufallsgenerator könnte eine spannende Thematik für die Fallstudie sein.  

In [ ]:
# Bibliothek laden
import random as rd
# Zufallszahlen
zz = rd.randrange(1, 10)
print("Erste Zufallszahl ist " + str(zz))

# Mehr Zufallszahlen
zz = rd.randrange(1, 1000)
print("Zweite Zufallszahl ist " + str(zz))


# Noch mehr Zufallszahlen
zz = rd.gauss(100, 1000)
print("Dritte Zufallszahl ist " + str(zz))




Erste Zufallszahl ist 3
Zweite Zufallszahl ist 977
Dritte Zufallszahl ist -265.79097196032586


# Operatoren

In Python gibt es verschiedene Operatoren, die sich den folgenden Gruppen zuornden lassen:


*   Arithmetische Operatoren
*   Zuordnungsoperatoren
*   Vergleichsoperatoren
*   Logische Operatoren
*   Identitätsoperatoren
*   Mitgliedsoperatoren
*   'Bitwise'-Operatoren

Wir haben bereits Arithmetische Operatoren (```+, -```) und auch Zuweisungsoperator ```=``` genutzt. Nachfolgend werden wir zusätzlich Vergleichsoperatoren und logische Operatoren nutzen.

Eine Beschreibung der Operatoren mit Beispielen kann [hier](https://www.programiz.com/python-programming/operators) nachgelesen werden. 

In [ ]:
# Bibliothek importieren
import random as rd
# Beispielzahlen erzeugen
a = rd.randrange(2,100,2) # gerade Zahl
print('a ist ', a)
b = rd.randrange(1,99,2) # ungerade Zahl
print('b ist ', b)
# Vergleichsoperator
# Gleichheit
print('a == b',a==b)
# Ungleichheit
print('a != b',a!=b)
# Größer gleich
print('a >= b',a>=b)
# Kleiner gleich
print('a <= b',a<=b)
# Größer 
print('a > b',a>b)
# Kleiner 
print('a < b',a<b)

# Logische Operatoren sind and und or
print('(a >= 2) and (b >= 1) ist ',(a >= 2) and (b >= 1))
print('(a >= 2) or (b >= 100) ist ',(a >= 2) or (b >= 100))
print('not ((a >= 2) or (b >= 100)) ist ',not ((a >= 2) or (b >= 100)))


a ist  10
b ist  77
a == b False
a != b True
a >= b False
a <= b True
a > b False
a < b True
(a >= 2) and (b >= 1) ist  True
(a >= 2) or (b >= 100) ist  True
not ((a >= 2) or (b >= 100)) ist  False


# Kontrollstrukturen

Kontrollstrukturen dienen uns zur Ablaufsteuerung unseres Codes. Dabei wird die Reihenfolge von uns vorgegeben, in der unsere Berechnungen (aka Algorithmus) nacheinander ausgeführt werden. Zusätzlich können wir mit Kontrollstrukturen unsere Codes so schreiben, dass sie auf verschiedene Zustände reagieren. Gängig sind die Fälle, in denen Programmteile nur bedingt (bedingte Anweisung) oder wiederholt (Schleife) ausgeführt werden.

Die bedingten Anweisungen erfolgen über die Wenn-Dann-Strukturen (```if...then...else```) und die wiederholte Anweisung erfolgt über die Schleifen (```for, while```).

Nachfolgend schauen wir uns einige Beispiele an.

In [ ]:
# Bibliothek importieren
import random as rd
# Beispielzahlen erzeugen
a = rd.randrange(1,200,2) 
print('a ist ', a)
b = rd.randrange(1,200,2) 
print('b ist ', b)

# WENN-DANN-Abzweigung
if b>a:
  print("b ist größer als a")

# WENN-SONST-DANN Abzweicgung
if b>a:
  print("b ist größer als a")
else:
  print("b ist kleiner als a oder sie sind gleich")

# WENN_WENN-SONST-DANN Abzweicgung
if b>a:
  print("b ist größer als a")
elif b==a:
  print("b und a sind gleich")
else:
  print("b ist kleiner als a")



a ist  75
b ist  165
b ist größer als a
b ist größer als a
b ist größer als a


In [ ]:
# Bibliothek importieren
import numpy as np
# Beispielzahlen erzeugen
a = np.random.rand(5,1) # 
print('a ist ', a)

# Erste Schleifen
for x in a:
  print('Zahl ist ', x)

# Verknüpfung zwischen for-Schleife und if-Bedingug
for x in a:
  print('Zahl ist ', x)
  if x<0.5:
    print('Diese Zahl ist besonders. Sie ist ', x)

# Verschachtelte Schleifen
# Beispielzahlen erzeugen
a = np.random.rand(5,5) # 
print('a ist ', a)

a ist  [[0.73710566]
 [0.71218389]
 [0.78098149]
 [0.39608276]
 [0.59652393]]
Zahl ist  [0.73710566]
Zahl ist  [0.71218389]
Zahl ist  [0.78098149]
Zahl ist  [0.39608276]
Zahl ist  [0.59652393]
Zahl ist  [0.73710566]
Zahl ist  [0.71218389]
Zahl ist  [0.78098149]
Zahl ist  [0.39608276]
Diese Zahl ist besonders. Sie ist  [0.39608276]
Zahl ist  [0.59652393]
a ist  [[0.98549559 0.69341762 0.35134387 0.57160665 0.79987124]
 [0.67070061 0.40377168 0.9366913  0.55343028 0.29155531]
 [0.3288978  0.45700179 0.23194792 0.91963206 0.9392139 ]
 [0.38626189 0.81901452 0.31812694 0.73101717 0.73632936]
 [0.67835774 0.23686596 0.78953648 0.65531505 0.85305741]]


In [ ]:
# Bibliothek importieren
import numpy as np
# Beispielzahlen erzeugen
a = np.random.rand(5,5) # 
print('a ist ', a)

# Verschachtelte Schleifen
for x in range(1,6):
  for y in range(1,6):
    print('Die Zahl ist ', a[x-1,y-1])



a ist  [[0.39571741 0.02225674 0.20514816 0.77108737 0.33381187]
 [0.69268354 0.96695302 0.45572892 0.46545474 0.70313635]
 [0.22532698 0.09642449 0.06567685 0.60235739 0.17155767]
 [0.26078283 0.76442513 0.16003552 0.17800682 0.53345887]
 [0.18906965 0.15433472 0.94260534 0.91053398 0.3718003 ]]
Die Zahl ist  0.3957174061846286
Die Zahl ist  0.02225674498787622
Die Zahl ist  0.2051481639772491
Die Zahl ist  0.771087372766889
Die Zahl ist  0.33381187376450694
Die Zahl ist  0.6926835416036455
Die Zahl ist  0.9669530163945075
Die Zahl ist  0.45572892233527484
Die Zahl ist  0.4654547434938119
Die Zahl ist  0.7031363512201356
Die Zahl ist  0.22532698130173112
Die Zahl ist  0.0964244906125612
Die Zahl ist  0.06567684597112888
Die Zahl ist  0.6023573860654354
Die Zahl ist  0.17155767408588796
Die Zahl ist  0.2607828344069688
Die Zahl ist  0.7644251257426623
Die Zahl ist  0.16003551553944972
Die Zahl ist  0.17800681602766932
Die Zahl ist  0.5334588667031303
Die Zahl ist  0.18906965298258582
D

# Funktionen

Skripte sind die Codes, die wir bisher erstellt haben. Neben den Skripten, die zur Ablaufsteuerung von Programmen dienen, können wir auch Funktionen anlegen. Funktionen dienen zur Auslagerung von Berechnungsschritten, die wiederholt benötigt werden. Im Unterschied zu einem Skript ist eine Funktion nicht für sich selbst lauffähig; sie muss aus einem Skript aufgerufen werden.

Eine Funktion wird in Python mit dem Schlüsselwort ```def``` eingeleitet. Danach folgt der Name der Funktion (gleiche Anforderung wie bei den Variablennamen), ggf. Input-Variablen und im Anschluss die eigentliche Berechnung.


In [ ]:
# Beispiel einer Funktion
def unsere_erste_funktion():
  print('Wow, das ist ist erste Funnktion')

In [ ]:
# Sie liefert nur dann ein Ergebnis, wenn sie aufgerufen wird
#def unsere_erste_funktion():
#  print('Wow, das ist ist erste Funnktion')

unsere_erste_funktion()


Wow, das ist ist erste Funnktion


Wenn wir die Funktionen nicht nur wiederholt, sondern auch aus unterschiedlichen Skripten aufrufen wollen, dann erstellen wir ein Modul und importieren es.

Ein Modul ist eine Datei, die eine Reihe von Funktionen enthält, die wir in unserer Anwendung aufnehmen möchten. Das Modul wird dann mittels ```import``` in unser Skript aufgenommen.



## PyCharm: Eine IDE für Python-Skripte

Während ich im Kurs Colab-Notebooks verwende, werden Python-Codes in produktiven Umgebungen in Firmen, öffentlicher Verwaltung und akademischen Institutionen aus Skriptdateien mit der Endung `.py` ausgeführt. Colab bietet einen einfachen Texteditor zum Schreiben dieser Skriptdateien, aber die meisten Entwickler:innen verwenden eine spezielle Softwareanwendung, eine sogenannte "integrierte Entwicklungsumgebung" (IDE), um diese Skripte zu schreiben. 

Von den vielen möglichen alternativen IDEs nutzen wir PyCharm, ein kostenloses Tool für diese Entwicklungen. Es handelt sich um einen einfachen Code-Editor mit einer Vielzahl möglicher Erweiterungen. Es gibt eine Vielzahl anderer freier IDEs (u.a. von Microsoft), die für Ihre Zwecke besser geeignet ist. Es spielt keine Rolle, welche IDE genutzt wird, da die Skriptdateien mit der Endung `.py` von allen IDEs ausgeführt werden.  

PyCharm kann von [hier](https://www.jetbrains.com/products/compare/?product=pycharm&product=pycharm-ce) heruntergeladen werden und Tutorials können über die [Dokumentation](https://www.jetbrains.com/help/pycharm/quick-start-guide.html) abgerufen werden.

Wenn Sie Linux oder Mac nutzen, dann ist Python bereits installiert, aber Sie haben noch keine IDE.




